### ISSUE TITLE
Consider replacing `IObjectTypeShape.GetProperties()` with an `IReadOnlyList<T>`

### ISSUE THREAD

**Issue by eiriktsarpalis** [eiriktsarpalis/PolyType#77]
The existing [`IObjectTypeShape.GetProperties()`](https://eiriktsarpalis.github.io/PolyType/api/PolyType.Abstractions.IObjectTypeShape.html#PolyType_Abstractions_IObjectTypeShape_GetProperties) and [`IConstructorShape.GetParameters()`](https://eiriktsarpalis.github.io/PolyType/api/PolyType.Abstractions.IConstructorShape.html#PolyType_Abstractions_IConstructorShape_GetParameters) methods return an `IEnumerable` of results. This somewhat made sense back when this library only worked on top of reflection and resolving individual properties was expensive, but it creates usability problems for users needing to interrogate whether an object contains properties or not.

The methods should be replaced with properties returning `IReadOnlyList<T>` values instead.

cc @AArnott

**Comment by AArnott** [comment]
> it creates usability problems for users needing to interrogate whether an object contains properties or not.

For that, I've used `HasProperties`. But ya, it's an odd pattern and I favor a list type instead.
