### ISSUE TITLE
Unsafe accessor generated for SerializationGuard

### ISSUE THREAD

**Issue by AArnott** [eiriktsarpalis/PolyType#86]
iOS AOT compilation fails in part due to this error:

> Unable to compile method 'void System.Runtime.Serialization.SerializationGuard:<ThrowIfDeserializationInProgress>g__ThrowIfDeserializationInProgress|0_0 (System.Runtime.Serialization.SerializationInfo,string,int&)' due to: 'Method has zero rva'.

Why is that being generated? That method is defined [in .NET](https://source.dot.net/#System.Private.CoreLib/src/libraries/System.Private.CoreLib/src/System/Runtime/Serialization/[SerializationInfo.SerializationGuard.cs](https://source.dot.net/#System.Private.CoreLib/src/libraries/System.Private.CoreLib/src/System/Runtime/Serialization/SerializationInfo.SerializationGuard.cs,597c453495bd7491),597c453495bd7491).

_Originally posted by @AArnott in https://github.com/eiriktsarpalis/PolyType/issues/73#issuecomment-2542590612_

**Comment by eiriktsarpalis** [comment]
This doesn't look like an unsafe accessor generated by PolyType -- it's a throw helper from BCL. What's the stacktrace?

**Comment by AArnott** [comment]
> How is the method being rooted?

What does that mean? If you're asking what references it, is there any guarantee that it's being referenced? After all, the other unsafe accessors that your source generator _does_ emit itself didn't seem to be referenced, yet the AOT compiler complained about them.

**Comment by eiriktsarpalis** [comment]
> What does that mean? If you're asking what references it, is there any guarantee that it's being referenced?

I'm assuming that it should be referenced somehow, otherwise it would have been trimmed away. But this seems unrelated to the presence of unsafe accessors per se.

> After all, the other unsafe accessors that your source generator _does_ emit itself didn't seem to be referenced, yet the AOT compiler complained about them.

Does it still do this after my most recent fix? Can you share a repro?

**Comment by AArnott** [comment]
> Does it still do this after my most recent fix? Can you share a repro?

#84 tracks the only remaining problem I thought you had. The C# lang svc said it wasn't referenced, but apparently it is (from another generated file?).

But if your earlier fix was to suppress generation of something that actually wasn't referenced, then that shows that the trimmer either isn't removing it, or it removes it only _after_ the AOT compiler fails to process it on iOS for .NET 8.

**Comment by eiriktsarpalis** [comment]
The generated code you shared in #84 does in fact use the accessor. It's tucked inside the body of `ParameterizedConstructorFunc`.

**Comment by AArnott** [comment]
I'll close this until I have evidence that it's coming from your source generator (since it sounds like you don't expect it to be).
